drop table if exists article_tag;
drop table if exists article;
drop table if exists tag;
drop table if exists category;

create table category (
    id bigint generated by default as identity primary key,
    name varchar(50) not null unique,
    description varchar(200),
    sort_order integer not null default 0,
    status varchar(20) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table tag (
    id bigint generated by default as identity primary key,
    name varchar(50) not null unique,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table article (
    id bigint generated by default as identity primary key,
    category_id bigint,
    title varchar(120) not null,
    summary varchar(300),
    content text not null,
    cover_url varchar(500),
    status varchar(20) not null,
    is_top boolean not null default false,
    is_recommend boolean not null default false,
    view_count integer not null default 0,
    comment_count integer not null default 0,
    published_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_article_category foreign key (category_id) references category (id)
);

create table article_tag (
    article_id bigint not null,
    tag_id bigint not null,
    constraint uk_article_tag unique (article_id, tag_id),
    constraint fk_article_tag_article foreign key (article_id) references article (id) on delete cascade,
    constraint fk_article_tag_tag foreign key (tag_id) references tag (id) on delete cascade
);
