package com.xinmengqaq.springboot.article.mapper;

import com.xinmengqaq.springboot.article.dto.CategoryQueryDTO;
import com.xinmengqaq.springboot.article.entity.Category;
import com.xinmengqaq.springboot.article.vo.CategoryVO;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.annotation.MapperScan;
import org.mybatis.spring.boot.test.autoconfigure.MybatisTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import org.springframework.test.context.jdbc.Sql;

import java.time.OffsetDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@MybatisTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:category_mapper_test;MODE=PostgreSQL;DATABASE_TO_UPPER=false",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "mybatis.mapper-locations=classpath*:mapper/**/*.xml",
        "mybatis.configuration.map-underscore-to-camel-case=true"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@MapperScan("com.xinmengqaq.springboot.article.mapper")
@Sql(statements = {
        "drop table if exists article",
        "drop table if exists category",
        "create table category (id bigint generated by default as identity primary key, name varchar(50) not null unique, description varchar(200), sort_order integer not null default 0, status varchar(20) not null check (status in ('visible', 'hidden')), created_at timestamp with time zone not null, updated_at timestamp with time zone not null)",
        "create table article (id bigint generated by default as identity primary key, category_id bigint, title varchar(120) not null, summary varchar(300), content text not null, cover_url varchar(500), status varchar(20) not null, is_top boolean not null default false, is_recommend boolean not null default false, view_count integer not null default 0, comment_count integer not null default 0, published_at timestamp with time zone, created_at timestamp with time zone not null, updated_at timestamp with time zone not null)",
        "insert into category (id, name, description, sort_order, status, created_at, updated_at) values (1, 'Java', 'Java 学习', 1, 'visible', timestamp with time zone '2026-07-09 09:00:00+08:00', timestamp with time zone '2026-07-09 09:00:00+08:00')",
        "insert into category (id, name, description, sort_order, status, created_at, updated_at) values (2, '随笔', '生活随笔', 2, 'hidden', timestamp with time zone '2026-07-09 10:00:00+08:00', timestamp with time zone '2026-07-09 10:00:00+08:00')",
        "insert into category (id, name, description, sort_order, status, created_at, updated_at) values (3, '空分类', null, 0, 'visible', timestamp with time zone '2026-07-09 11:00:00+08:00', timestamp with time zone '2026-07-09 11:00:00+08:00')",
        "alter table category alter column id restart with 4",
        "insert into article (category_id, title, content, status, created_at, updated_at) values (1, 'Java 文章 1', '正文', 'draft', timestamp with time zone '2026-07-09 12:00:00+08:00', timestamp with time zone '2026-07-09 12:00:00+08:00')",
        "insert into article (category_id, title, content, status, created_at, updated_at) values (1, 'Java 文章 2', '正文', 'published', timestamp with time zone '2026-07-09 13:00:00+08:00', timestamp with time zone '2026-07-09 13:00:00+08:00')",
        "insert into article (category_id, title, content, status, created_at, updated_at) values (2, '随笔文章', '正文', 'hidden', timestamp with time zone '2026-07-09 14:00:00+08:00', timestamp with time zone '2026-07-09 14:00:00+08:00')"
})
class CategoryMapperTest {

    @Autowired
    private CategoryMapper categoryMapper;

    @Test
    @DisplayName("查询分类列表时返回文章数量并按排序值和ID稳定排序")
    void testSelectListVOReturnsArticleCountAndStableOrder() {
        CategoryQueryDTO queryDTO = new CategoryQueryDTO();

        List<CategoryVO> categories = categoryMapper.selectListVO(queryDTO);

        assertThat(categories).extracting(CategoryVO::getName)
                .containsExactly("空分类", "Java", "随笔");
        assertThat(categories).extracting(CategoryVO::getArticleCount)
                .containsExactly(0L, 2L, 1L);
    }

    @Test
    @DisplayName("查询分类列表传 visible 状态时只返回显示分类")
    void testSelectListVOFiltersByStatus() {
        CategoryQueryDTO queryDTO = new CategoryQueryDTO();
        queryDTO.setStatus("visible");

        List<CategoryVO> categories = categoryMapper.selectListVO(queryDTO);

        assertThat(categories).extracting(CategoryVO::getName)
                .containsExactly("空分类", "Java");
    }

    @Test
    @DisplayName("按ID查询分类VO时返回文章数量")
    void testSelectByIdVOReturnsArticleCount() {
        CategoryVO category = categoryMapper.selectByIdVO(1L);

        assertThat(category.getName()).isEqualTo("Java");
        assertThat(category.getArticleCount()).isEqualTo(2L);
    }

    @Test
    @DisplayName("修改分类查重时会排除当前分类自己")
    void testSelectExistsByIdAndNameExcludesCurrentCategory() {
        Category self = categoryMapper.selectExistsByIdAndName(1L, "Java");
        Category other = categoryMapper.selectExistsByIdAndName(3L, "Java");

        assertThat(self).isNull();
        assertThat(other).isNotNull();
        assertThat(other.getId()).isEqualTo(1L);
    }

    @Test
    @DisplayName("新增分类时可省略描述并回填自增ID")
    void testInsertAllowsNullableDescriptionAndBackfillsId() {
        Category category = category("数据库", null, 3, "visible");

        int rows = categoryMapper.insert(category);

        assertThat(rows).isEqualTo(1);
        assertThat(category.getId()).isNotNull();
        Category saved = categoryMapper.selectById(category.getId());
        assertThat(saved.getName()).isEqualTo("数据库");
        assertThat(saved.getDescription()).isNull();
    }

    @Test
    @DisplayName("修改分类时会按ID更新基础字段")
    void testUpdateByIdUpdatesCategoryFields() {
        Category category = category("Java 后端", "后端学习", 5, "hidden");
        category.setId(1L);

        int rows = categoryMapper.updateById(category);

        assertThat(rows).isEqualTo(1);
        CategoryVO updated = categoryMapper.selectByIdVO(1L);
        assertThat(updated.getName()).isEqualTo("Java 后端");
        assertThat(updated.getDescription()).isEqualTo("后端学习");
        assertThat(updated.getSortOrder()).isEqualTo(5);
        assertThat(updated.getStatus()).isEqualTo("hidden");
        assertThat(updated.getArticleCount()).isEqualTo(2L);
    }

    @Test
    @DisplayName("删除分类前可以统计占用文章数量，未占用分类可以删除")
    void testCountArticleByCategoryIdAndDeleteById() {
        Long articleCount = categoryMapper.countArticleByCategoryId(1L);

        assertThat(articleCount).isEqualTo(2L);
        assertThat(categoryMapper.countArticleByCategoryId(3L)).isZero();

        int rows = categoryMapper.deleteById(3L);

        assertThat(rows).isEqualTo(1);
        assertThat(categoryMapper.selectById(3L)).isNull();
    }

    private Category category(String name, String description, Integer sortOrder, String status) {
        OffsetDateTime now = OffsetDateTime.parse("2026-07-09T15:00:00+08:00");
        Category category = new Category();
        category.setName(name);
        category.setDescription(description);
        category.setSortOrder(sortOrder);
        category.setStatus(status);
        category.setCreatedAt(now);
        category.setUpdatedAt(now);
        return category;
    }

    @SpringBootConfiguration
    static class TestApplication {
    }
}
