package com.xinmengqaq.springboot.article.mapper;

import com.xinmengqaq.springboot.article.dto.TagQueryDTO;
import com.xinmengqaq.springboot.article.entity.Tag;
import com.xinmengqaq.springboot.article.vo.TagVO;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.annotation.MapperScan;
import org.mybatis.spring.boot.test.autoconfigure.MybatisTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import org.springframework.test.context.jdbc.Sql;

import java.time.OffsetDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@MybatisTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:tag_mapper_test;MODE=PostgreSQL;DATABASE_TO_UPPER=false",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "mybatis.mapper-locations=classpath*:mapper/**/*.xml",
        "mybatis.configuration.map-underscore-to-camel-case=true"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@MapperScan("com.xinmengqaq.springboot.article.mapper")
@Sql(statements = {
        "drop table if exists article_tag",
        "drop table if exists article",
        "drop table if exists tag",
        "create table tag (id bigint generated by default as identity primary key, name varchar(50) not null unique, created_at timestamp with time zone not null, updated_at timestamp with time zone not null)",
        "create table article (id bigint generated by default as identity primary key, title varchar(120) not null, content text not null, status varchar(20) not null, created_at timestamp with time zone not null, updated_at timestamp with time zone not null)",
        "create table article_tag (article_id bigint not null, tag_id bigint not null, unique (article_id, tag_id))",
        "insert into tag (id, name, created_at, updated_at) values (1, 'Java', timestamp with time zone '2026-07-09 09:00:00+08:00', timestamp with time zone '2026-07-09 09:00:00+08:00')",
        "insert into tag (id, name, created_at, updated_at) values (2, '生活', timestamp with time zone '2026-07-09 10:00:00+08:00', timestamp with time zone '2026-07-09 10:00:00+08:00')",
        "insert into tag (id, name, created_at, updated_at) values (3, '空标签', timestamp with time zone '2026-07-09 11:00:00+08:00', timestamp with time zone '2026-07-09 11:00:00+08:00')",
        "alter table tag alter column id restart with 4",
        "insert into article (id, title, content, status, created_at, updated_at) values (1, 'Java 文章 1', '正文', 'draft', timestamp with time zone '2026-07-09 12:00:00+08:00', timestamp with time zone '2026-07-09 12:00:00+08:00')",
        "insert into article (id, title, content, status, created_at, updated_at) values (2, 'Java 文章 2', '正文', 'published', timestamp with time zone '2026-07-09 13:00:00+08:00', timestamp with time zone '2026-07-09 13:00:00+08:00')",
        "insert into article (id, title, content, status, created_at, updated_at) values (3, '生活文章', '正文', 'hidden', timestamp with time zone '2026-07-09 14:00:00+08:00', timestamp with time zone '2026-07-09 14:00:00+08:00')",
        "insert into article_tag (article_id, tag_id) values (1, 1)",
        "insert into article_tag (article_id, tag_id) values (2, 1)",
        "insert into article_tag (article_id, tag_id) values (3, 2)"
})
class TagMapperTest {

    @Autowired
    private TagMapper tagMapper;

    @Test
    @DisplayName("查询标签列表时返回文章数量并按ID倒序")
    void testSelectListReturnsArticleCountAndStableOrder() {
        TagQueryDTO queryDTO = new TagQueryDTO();

        List<TagVO> tags = tagMapper.selectList(queryDTO);

        assertThat(tags).extracting(TagVO::getName)
                .containsExactly("空标签", "生活", "Java");
        assertThat(tags).extracting(TagVO::getArticleCount)
                .containsExactly(0L, 1L, 2L);
    }

    @Test
    @DisplayName("查询标签列表传关键词时只返回匹配标签")
    void testSelectListFiltersByKeyword() {
        TagQueryDTO queryDTO = new TagQueryDTO();
        queryDTO.setKeyword("生");

        List<TagVO> tags = tagMapper.selectList(queryDTO);

        assertThat(tags).extracting(TagVO::getName)
                .containsExactly("生活");
    }

    @Test
    @DisplayName("按ID查询标签VO时返回文章数量")
    void testSelectByIdVOReturnsArticleCount() {
        TagVO tag = tagMapper.selectByIdVO(1L);

        assertThat(tag.getName()).isEqualTo("Java");
        assertThat(tag.getArticleCount()).isEqualTo(2L);
    }

    @Test
    @DisplayName("修改标签查重时会排除当前标签自己")
    void testSelectExistsByIdAndNameExcludesCurrentTag() {
        Tag self = tagMapper.selectExistsByIdAndName(1L, "Java");
        Tag other = tagMapper.selectExistsByIdAndName(3L, "Java");

        assertThat(self).isNull();
        assertThat(other).isNotNull();
        assertThat(other.getId()).isEqualTo(1L);
    }

    @Test
    @DisplayName("新增标签时会回填自增ID")
    void testInsertBackfillsId() {
        Tag tag = tag("数据库");

        long rows = tagMapper.insert(tag);

        assertThat(rows).isEqualTo(1);
        assertThat(tag.getId()).isNotNull();
        Tag saved = tagMapper.selectById(tag.getId());
        assertThat(saved).isNotNull();
        assertThat(saved.getName()).isEqualTo("数据库");
    }

    @Test
    @DisplayName("删除标签前可以统计占用文章数量，未占用标签可以删除")
    void testCountArticleByTagIdAndDeleteById() {
        Long articleCount = tagMapper.countArticleByTagId(1L);

        assertThat(articleCount).isEqualTo(2L);
        assertThat(tagMapper.countArticleByTagId(3L)).isZero();

        int rows = tagMapper.deleteById(3L);

        assertThat(rows).isEqualTo(1);
        assertThat(tagMapper.selectById(3L)).isNull();
    }

    private Tag tag(String name) {
        OffsetDateTime now = OffsetDateTime.parse("2026-07-09T15:00:00+08:00");
        Tag tag = new Tag();
        tag.setName(name);
        tag.setCreatedAt(now);
        tag.setUpdatedAt(now);
        return tag;
    }

    @SpringBootConfiguration
    static class TestApplication {
    }

}
